---
apiVersion: v1
kind: Service
metadata:
  name: weather
  labels:
    app: weather
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32718
    protocol: TCP
  selector:
    app: weather
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weather-deploy
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather-pod
        image: myregistry:5000/service-weather-node:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: config
              key: environment
        - name: MONGO_ENABLED
          value: "true"